### ISSUE TITLE
Provide a single fact on the commandline

### ISSUE THREAD

**Issue by ahpook** [lyraproj/hiera#20]
In addition to the `--facts` flag (which needs an input file in yaml or json), it'd be cool if the `lookup` command had a way to pass fact name/value on the command line. This would make it easy and fast to test hierarchy or data changes. I'd suggest a syntax like

`lookup --fact name1=value1 --fact name2=value2`

**Comment by thallgren** [comment]
Alternative proposal:
Allowed the facts to be read from `stdin` by using a dash as the name of the facts file. The above example would look like this:
```
lookup something --facts - <<END
name1: value1
name2: value2
END
```
Pros:
- No need to repeat an option
- No need for an additional option
- Full YAML syntax available (arrays, hashes, etc.)
- Very minor adjustments needed in existing code.
- Can also read facts using a pipe.

Cons:
- The added start/end tag when used as in the example.

Idea copied from [PUP-8500](https://tickets.puppetlabs.com/browse/PUP-8500?focusedCommentId=539674&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-539674)

**Comment by dhollinger** [comment]
@thallgren While I believe that having that as an alternative would be valuable, after speaking with some teammates (who are also excited about go-hiera), they'd feel more comfortable with options similar to what @ahpook posted.

**Comment by thallgren** [comment]
@dhollinger I'm fine with that and I don't think one excludes the other.
I need a couple of things regarding the `<key>=<value>` syntax clarified.
1. What rules should apply when parsing the value? Should we limit the value to primitives, i.e. null, number, boolean, and string?
2. If the answer to #1 is yes, how do we handle quotes and possible escaped quotes in such a string and keep it from conflicting with shell quotes and escapes?
3. If the answer to #1 is no, then what type of parsing do we want to use for more complex values?
4. How do we interpret a dotted key? Do we want that to emulate a key into a nested hash?
