### ISSUE TITLE
Docs are insufficient

### ISSUE THREAD

**Issue by jorhett** [lyraproj/hiera#23]
As Go doesn't install modules by default, the documentation doesn't work as shown.

```
$ go get github.com/lyraproj/hiera
package github.com/lyraproj/hiera: no Go files in /Users/jrhett/go/src/github.com/lyraproj/hiera

$ go install github.com/lyraproj/hiera/lookup
../../go/src/github.com/lyraproj/hiera/internal/location.go:8:2: cannot find package "github.com/bmatcuk/doublestar" in any of:
	/usr/local/Cellar/go/1.12.6/libexec/src/github.com/bmatcuk/doublestar (from $GOROOT)
	/Users/jrhett/go/src/github.com/bmatcuk/doublestar (from $GOPATH)
```

I suspect many potential users are not aware enough of Go's module management to do the clone of the repo and install the modules, so at least mentioning it is probably a good idea. Or outright mention `GO111MODULE=on go get github.com/lyraproj/hiera` as the quick fix ;)

**Comment by thallgren** [comment]
The docs are missing a crucial piece of info. You need:
```
export GO111MODULE=on
```
in order for things to work. I'll add that to the readme.
