### ISSUE TITLE
Please add example how to use hiera from code

### ISSUE THREAD

**Issue by hlindberg** [lyraproj/hiera#39]
I need to do the following in golang code:

* perform a lookup of keys as directed by an "environment" level hiera.yaml (my app to provide the path)
* then, perform a lookup of a module specific key in each module on the modulepath - need to loop over the lookups so happy to accept  having to set up a new instance per module. (My app to provide the path)
* In each lookup I need to be able to set a number of facts/variables for hiera to interpolate.
* I want to be able to do a deep merge of what I looked up in the same way as hiera does this. (My app will make these calls as it is looking up different keys that it merges - for example `mykey`, `module_a::mykey`, `module_b::mykey` - I am not expecting hiera to do that for me).
* I want to be able to (optionally) turn on "explain" output to allow users to debug these lookups
* I only need standard backends (yaml)
* I would like the `hiera.yaml` files involved to look exactly the same as in the Ruby version (to allow the ruby version of my application to use exactly the same configuration and data files).

**Comment by thallgren** [comment]
Closed by #40
