### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by hbuckle** [lyraproj/hiera#41]
Any chance of tagging up some releases for this and the plugins?
Thanks

**Comment by ahpook** [comment]
I'm working on this! Gonna set up some github actions for this.

**Comment by ahpook** [comment]
Reopening, this isn't completely done. Per conversation in slack we're going to make a new repo that does the necessary composition to pull in core hiera + plugins and build images/releases from there.

**Comment by thallgren** [comment]
This project and all its dependencies now have tagged releases so I'm closing this ticket. Creating a new repo to pull in all plugins will be easier with the tags present, but that is a task in itself that belongs in a different ticket.
