### ISSUE TITLE
Prevent unnecessary attempts to publish a docker image

### ISSUE THREAD

**Issue by thallgren** [lyraproj/hiera#48]
The workflow to build and publish docker image runs on every push, regardless of repository. In my thallgren fork, the build fails because I don't have the correct credentials to publish (which is probably for the good in this case).

Example of failure: https://github.com/thallgren/hiera/runs/284812108

**Comment by ahpook** [comment]
Think this is addressed by #53 , can you confirm?

**Comment by thallgren** [comment]
Yes. Thanks!
