### ISSUE TITLE
TLS changes prevent non-tls restserver from starting

### ISSUE THREAD

**Issue by ahpook** [lyraproj/hiera#62]
After the changes in #60 , I cannot start hieraserver either standalone or in a container.

I think the problem is this bit:
https://github.com/lyraproj/hiera/blob/a04027d375258ee72d645b6d0a56b47fc4dd2a1b/hieraserver/rest/rest.go#L167-L171

Because `makeTLSConfig()` creates a new `tls.Config` instance *before* it checks whether ssl keys and certs are passed in, the variable is never `nil`; it contains an instantiated but non-working tls configuration.

**Comment by ahpook** [comment]
@flashvoid wdyt?

**Comment by flashvoid** [comment]
@ahpook ouch sorry, you are correct, this indeed should be initialized after the check.
