### ISSUE TITLE
LookupInto should support time.Duration in int or string form

### ISSUE THREAD

**Issue by hlindberg** [lyraproj/hiera#86]
It would be very convenient if `LookupInto` could handle `time.Duration` such that an integer value is interpreted as a nanosecond timestamp and that a string is interpreted in the `time.ParseDuration` string format (for example "14h52m"). At present this ends with a panic `	panic: reflect: call of reflect.Value.SetString on int64 Value`. 

The only current work around is to use `string` fields and post process the looked up result.

**Comment by thallgren** [comment]
I think the problem is that `dgo` lacks a proper mapping for the `time.Duration` type. With that in place, Hiera should work OK.

**Comment by thallgren** [comment]
This is fixed by using hiera v1.0.0-rc4 which uses dgo of the same version.
